config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  devise_scope :user do
    post 'users/sign_up/confirm' => 'users/registrations#confirm'
    get 'users/sign_up/complete' => 'users/registrations#complete'
    get 'users/edit_profile' => 'users/registrations#edit_profile'
    post 'users/update_profile' => 'users/registrations#update_profile'
    get 'users/identification' => 'users/registrations#identification'
    post 'users/update_identification' => 'users/registrations#update_identification'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'items#index'
  resources :users, only: [:index, :edit, :update] do
    collection do
      get 'confirm_sign_out'
      get 'sell_items_list'
    end
    resources :receiver_informations, only: [:new, :create, :edit, :update]
    resources :credit_cards, only: [:index, :new, :create, :destroy] do
      collection do
        get 'add'
        post 'add_create'
      end
    end
  end
  resources :items, only: [:index, :new, :create, :show, :destroy,:edit,:update] do
    member do
      get 'buy_confirm'
      patch 'buy'
      get 'buy_complete'
    end
    collection do
      post 'search'
      post 'detail_search'
      get 'get_middle_categories', defaults: { format: 'json' }
      get 'get_small_categories', defaults: { format: 'json' }
      get 'get_item_sizes', defaults: { format: 'json' }
      get 'get_sizes_brand_allow', defaults: { format: 'json' }
    end
  end
  resources :large_categories, only: [:index, :show]
  resources :middle_categories, only: [:show]
  resources :small_categories, only: [:show]
  resources :brands, only: [:show]
  resources :brand_upper_categories, only: [:show]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  validates :password, length: { minimum: 6 }
  validates :family_name, presence: true,
                          zenkaku: true
  validates :first_name, presence: true,
                        zenkaku: true
  validates :family_name_kana, presence: true,
                              zenkaku_kana: true
  validates :first_name_kana, presence: true,
                              zenkaku_kana: true
  validates :birth_year, presence: true
  validates :birth_month, presence: true
  validates :birth_day, presence: true
  validates :postal_code, postal_code: true

  with_options unless: proc { [:admin].include?(validation_context) } do
    validates :phone_number,  presence: true,
                              telphone: true
  end

  validates_specific :nickname
  validates_specific :postal_code

  enum prefecture: I18n.t('prefecture')

  has_one :credit_card
  has_one :receiver_information
  has_many :buyer_items, class_name: 'Item', foreign_key: 'buyer_id'
  has_many :seller_items, class_name: 'Item', foreign_key: 'seller_id'
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :confirm_signed_in, except: [:new, :create, :confirm]
  before_action :set_large_categories, only: [:edit_profile, :identification]
  before_action :set_brands, only: [:edit_profile, :identification]

  # GET /resource/sign_up
  def new
    @user = User.new
    @page_number = 1
  end

  def confirm
    @user = User.new(configure_sign_up_params)
    @page_number = 1
    return render :new unless @user.valid?(:admin)
    @page_number = 2
    session[:user_1st_params] = configure_sign_up_params
  end

  # POST /resource
  def create
    @user = User.new(user_params)
    @page_number = 2
    return render :confirm unless @user.valid?
    @user.save
    sign_in @user
    session[:user_1st_params] = nil
    redirect_to new_user_receiver_information_path(current_user.id)
  end

  def complete
    @page_number = 5
  end

  def edit_profile
  end

  def update_profile
    @valid_user = User.new(update_profile_params)
    if validate_update_profile(@valid_user)
      current_user.update_columns(update_profile_params.to_hash)
      redirect_to users_path
    else
      render :edit_profile
    end 
  end

  def identification
  end

  def update_identification
    @valid_user = User.new(update_identification_params)
    if validate_update_identification(@valid_user)
      current_user.update_columns(update_identification_params.to_hash)
      redirect_to users_path
    else
      render :identification
    end 
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation, :family_name, :first_name, :family_name_kana, :first_name_kana, :birth_year, :birth_month, :birth_day)
  end

  def phone_number_params
    params.require(:user).permit(:phone_number)
  end

  def user_params
    session[:user_1st_params].merge(phone_number_params)
  end

  def update_profile_params
    params.require(:user).permit(:nickname, :profile)
  end

  def update_identification_params
    params.require(:user).permit(:postal_code, :prefecture, :city, :street, :building)
  end

  def confirm_signed_in
    return redirect_to new_user_session_path unless user_signed_in?
  end

  def validate_update_profile(user)
    return user.valid_nickname?
  end

  def validate_update_identification(user)
    return user.valid_postal_code?
  end

  def set_large_categories
    @large_categories = LargeCategory.all
  end

  def set_brands
    @brands = Brand.all
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_large_categories, only: [:index, :confirm_sign_out, :sell_items_list]
  before_action :set_brands, only: [:index, :confirm_sign_out, :sell_items_list]

  def index
  end
  def confirm_sign_out
  end
  def sell_items_list
    @sell_items = Item.where(seller_id: current_user.id).where(item_state_id:1).page(params[:page]).per(3)
    if session[:tmp_from_item_destroy] == true
      @from_item_destory = true
      session[:tmp_from_item_destroy] = nil
    else
      @from_item_destory = false
    end
  end

  private

  def set_large_categories
    @large_categories = LargeCategory.all
  end

  def set_brands
    @brands = Brand.all
  end
end

app/views/users/sell_items_list/_body.html.haml
.main-page__body
  .main-page__body__content
    - if from_item_destory == true
      .main-page__body__content__notification.main-page__body__content__notification--success
        商品を削除しました
        = fa_icon 'times', class: "main-page__body__content__notification__icon-close"
    %section.main-page__body__content__tab-container
      %h2.main-page__body__content__tab-container__head-title
        出品した商品
      %ul.main-page__body__content__tab-container__title-list
        %li.main-page__body__content__tab-container__title-list__item.main-page__body__content__tab-container__title-list__item--sell-item-list.main-page__body__content__tab-container__title-list__item--active
          %h3.main-page__body__content__tab-container__title-list__item__title
            = link_to '出品中', '', class: 'main-page__body__content__tab-container__title-list__item__link'
        %li.main-page__body__content__tab-container__title-list__item.main-page__body__content__tab-container__title-list__item--sell-item-list
          %h3.main-page__body__content__tab-container__title-list__item__title
            = link_to '取引中', '', class: 'main-page__body__content__tab-container__title-list__item__link'
        %li.main-page__body__content__tab-container__title-list__item.main-page__body__content__tab-container__title-list__item--sell-item-list
          %h3.main-page__body__content__tab-container__title-list__item__title
            = link_to '売却中', '', class: 'main-page__body__content__tab-container__title-list__item__link'
      .main-page__body__content__tab-container__content-list
        %ul.main-page__body__content__tab-container__content-list__content.main-page__body__content__tab-container__content-list__content--active
          - sell_items.each do |item|
            %li.main-page__body__content__tab-container__content-list__content__item
              = link_to item_path(item.id), class: 'main-page__body__content__tab-container__content-list__content__item__link' do
                %figure.main-page__body__content__tab-container__content-list__content__item__mercari-figure
                  = image_tag item.images.first.image.url, class: ['main-page__body__content__tab-container__content-list__content__item__mercari-figure__image', 'main-page__body__content__tab-container__content-list__content__item__mercari-figure__image--item']
                .main-page__body__content__tab-container__content-list__content__item__body
                  .main-page__body__content__tab-container__content-list__content__item__body__text
                    = item.name
                  .main-page__body__content__tab-container__content-list__content__item__body__contents
                    %span.main-page__body__content__tab-container__content-list__content__item__body__contents__index
                      = fa_icon 'heart', class: 'main-page__body__content__tab-container__content-list__content__item__body__contents__index__icon'
                      %span.main-page__body__content__tab-container__content-list__content__item__body__contents__index__number
                        0
                    %span.main-page__body__content__tab-container__content-list__content__item__body__contents__index
                      = fa_icon 'comment-alt', class: 'main-page__body__content__tab-container__content-list__content__item__body__contents__index__icon'
                      %span.main-page__body__content__tab-container__content-list__content__item__body__contents__index__number
                        0
                    .main-page__body__content__tab-container__content-list__content__item__body__contents__status-box
                      = item.item_state.name
                = fa_icon 'angle-right', class: 'main-page__body__content__tab-container__content-list__content__item__icon-arrow-right'
    = paginate(sell_items)
  = render 'users/sidebar/sidebar'